language: ruby
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-2.2.6
  - 1.8.7
matrix:
  allow_failures:
    - rvm: 1.8.7  
    - rvm: jruby-18mode